= javadoc macro examples


Below are some examples of using the `jenkinsdoc`, `staplerdoc`, and `javadoc`
macros.

The `jenkinsdoc` inline macro can be used to link to the Jenkins Javadoc at http://javadoc.jenkins.io/.

It supports a variety of different syntaxes. For classes in Jenkins core:

* jenkinsdoc:hudson.scm.SCM[] links to the full URL for the class in Jenkins core.
* jenkinsdoc:hudson.scm.SCM#all()[] links to the full URL for the class in Jenkins core, and includes a fragment.
* jenkinsdoc:SCM[] links to the `/byShortName` URL for the class in Jenkins core. Due to the redirect, fragments won't work here.

By default, all of these use the class name as label, but that can be customized if necessary by providing an alternative label between the square brackets.

jenkinsdoc:hudson.scm.SCM#all()[a list of all known SCM implementations]

The first class name component starting with an uppercase character is considered to start the class name. Everything before that component is considered to be part of the package name.

* jenkinsdoc:jenkins.model.lazy.BuildReference.HolderFactory[]
* jenkinsdoc:BuildReference.HolderFactory[]

---

For classes in plugins, the plugin's name (`artifactId`) is put before the class name and separated by colon:

* jenkinsdoc:git:hudson.plugins.git.GitSCM[] links to the full URL for the class in the git plugin.
* jenkinsdoc:git:hudson.plugins.git.GitSCM#getRepositories--[] links to the full URL for the class in the git plugin, and includes a fragment.

---

Two other inline macros, `staplerdoc` and `javadoc` exist and link to the
Stapler API documentation and Java API documentation, respectively.  These do
not support the form of `jenkinsci` that only requires the short name, but
otherwise work the same way.

Examples:

* javadoc:java.io.File#pathSeparator[the path separator]
* javadoc:java.nio.file.DirectoryStream.Filter[]
* staplerdoc:org.kohsuke.stapler.AncestorInPath[]
* staplerdoc:org.kohsuke.stapler.AncestorInPath.HandlerImpl[]